### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by lyxia** [hydro-sdk/counter-app#217]
Step:
1: git clone https://github.com/hydro-sdk/hydro_demo.git & cd hydro_demo
2: npm install
3: flutter pub get
4:node node_modules/@hydro-sdk/hydro-sdk/dist/compiler -t 'ota/hello-world.ts' -m 'hello-world' -d 'assets' -p debug -w 'ota'
5: run app

Expection: 

 Restarted application in 1,205ms.

flutter: I/Hydro 0 native, 646 virtual prototypes

flutter: attempt to call a nil value null with []

Error raised in:

  require

     defined in main_chunk:0

  anonymous closure

     defined in main_chunk:0

VM stacktrace follows:

@.hydroc/03f1598dde0a8071b05d51c2480ca193e15a89d217a291ca8a10f8d3d786a6ed/hello-world:7

  (_Lmain_chunk::d71c39187689639986b4a58c858b8f43c02ed5546a801bc21b68dbaea44632b1::require::file::0)

@.hydroc/03f1598dde0a8071b05d51c2480ca193e15a89d217a291ca8a10f8d3d786a6ed/hello-world:13123

  (null)

Dart stacktrace follows:

#0      Thread.attemptCall
_package:hydro_sdk/…/thread/thread.dart:42_

#1      call
_package:hydro_sdk/…/instructions/call.dart:28_

#2      Frame.cont
_package:hydro_sdk/…/vm/frame.dart:272_

#3      call
_package:hydro_sdk/…/instructions/call.dart:23_

#4      Frame.cont
_package:hydro_sdk/…/vm/frame.dart:272_

#5      Closure._dispatch
_package:hydro_sdk/…/vm/closure.dart:96_

#6      Closure.dispatch
_package:hydro_sdk/…/vm/closure.dart:83_

#7      HydroFunctionImpl.pcall<…>

════════ Exception caught by widgets library ═══════════════════════════════════

The following NoSuchMethodError was thrown building RunFromNetwork(dirty, state: _RunFromNetwork#04cf2):

Closure call with mismatched arguments: function ‘dispatch’
Receiver: Closure: (List<dynamic>) => Null
Tried calling: dispatch(Instance(length:0) of ‘_GrowableList’, parentState: Instance of ‘HydroState’)
Found: dispatch(List<dynamic>) => Null

The relevant error-causing widget was

RunFromNetwork
_lib/main.dart:7_

When the exception was thrown, this was the stack

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)

#1      _RunFromNetwork.build
_package:hydro_sdk/runFromNetwork.dart:300_

#2      StatefulElement.build
_package:flutter/…/widgets/framework.dart:4744_

#3      ComponentElement.performRebuild
_package:flutter/…/widgets/framework.dart:4627_

#4      StatefulElement.performRebuild
_package:flutter/…/widgets/framework.dart:4800_

…

════════════════════════════════════════════════════════════════════════════════

Application finished.

**Comment by chgibb** [comment]
Hi @lyxia , thanks for trying out Hydro!

I performed a fresh clone of `hydro_demo` (as of `5d31ca050f265104ab64f565d32d85e64ceacb09`) and can't seem to reproduce the error you're seeing. Could you provide some information? What operating system are you on? What kind of device are you running on? What version of Flutter are you using?

**Comment by lyxia** [comment]
Flutter 1.22.1 • channel stable
MacOS 10.15.7
Commit :5d31ca050f265104ab64f565d32d85e64ceacb09

**Comment by chgibb** [comment]
@lyxia have you made any changes to the demo repository before running?

**Comment by lyxia** [comment]
![image](https://user-images.githubusercontent.com/7269593/110198483-cecd9480-7e8d-11eb-9ebd-cd27fb361cc1.png)

**Comment by chgibb** [comment]
@lyxia what about any changes to the Typescript or Dart code?
