### ISSUE TITLE
shell nothing to create

### ISSUE THREAD

**Issue by lhjandroid** [hydro-sdk/counter-app#359]
hello I found you change the compile way of the ts file.but when i do the shell 
```
npx hydroc build --out-dir assets/ota --profile debug
All Hydro-SDK tools exist
Building project example-project
Building component counter-example
```
no any file out put,what should i do?

#package.json
```
{
  "name": "flutter_dm",
  "description": "",
  "scripts": {
    "test": "flutter test"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {},
  "dependencies": {
    "@hydro-sdk/hydro-sdk": "0.0.1-nightly.182",
    "@hydro-sdk/waveform": "0.0.1-nightly.34"
  }
}
```
#hydro.json
```
{
    "project": "example-project", // it can be any string?
    "components": [
        {
            "name": "counter-example", // it can be any string?
            "chunks": [
                {
                    "type": "mountable",
                    "baseUrl": "ota",
                    "entryPoint": "ota/index.ts"
                }
            ]
        }
    ]
}
```
and project's ota/index.ts file is exist

**Comment by lhjandroid** [comment]
sorry may be dowload ts2hc-darwin-x64 failed cause the reuslt

**Comment by chgibb** [comment]
Is there any more logs from `hydroc build`? What operating system are you on?

**Comment by lhjandroid** [comment]
on mac os,version 10.15.4,the console no more logs. can you provide the ts2hc-darwin-x64 download url?

**Comment by chgibb** [comment]
There's a directory named `.hydroc` . If you delete it and run the build command again, hydroc should download everything it needs. 

Is your Mac an M1 or Intel?

**Comment by lhjandroid** [comment]
download the ts2hc-darwin-x64 fail cause this.now it's ok.new question RunComponentFromFile the path what should be?

**Comment by chgibb** [comment]
Is your Mac an M1 or Intel?

**Comment by lhjandroid** [comment]
Intel,when download ts2hc-darwin-x64 sucess,it works well

**Comment by chgibb** [comment]
Good to hear! Let me know if you have any other questions / issues.
