### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by pvcresin** [hydro-sdk/counter-app#715]
I got a build error when I tried to run this sample.

## Step
1. Run `git clone git@github.com:hydro-sdk/counter-app.git` & `cd counter-app`
2. Run `npm install` and `flutter pub get`
3. Run `npx hydroc build --out-dir assets/ota --profile debug` -> error below
4. (Run `npx hydroc run` -> the same error)

```sh
All Hydro-SDK tools exist
Building project hydro-sdk
Building component counter-app

internal/bootstrap/pre_execution.js:106
    throw 'Invalid Nexe binary';
    ^
Invalid Nexe binary
(Use `ts2hc-darwin-x64 --trace-uncaught ...` to show where the exception was thrown)
```

It looks like all the sdk- tools are there.
![image](https://user-images.githubusercontent.com/7846521/146651280-f84da51f-4b92-4eb1-a3ca-52e37c75083f.png)

## Environment
- macOS Big Sur v11.6.1 (Intel Processor)
- VS Code + Flutter extension
- Node.js v16.13.0, npm v8.1.0
- Flutter v2.8.1, Dart v2.15.1

For now I just want to make sure it works. 🙏 
Please let me know if there is anything I need to change in the version of the tool.

P.S. I love the idea of Hydro-SDK!

**Comment by chgibb** [comment]
Hi @pvcresin thanks for checking out Hydro-SDK! 

`ts2hc` is built using [nexe](https://github.com/nexe/nexe) and is used internally by `build-project` (run by `npx hydroc build` and `run-project` (run by `npx hydroc run`). The error you reported is very odd. `ts2hc` is built in [Mac 10.15 on CI](https://github.com/hydro-sdk/hydro-sdk/blob/master/.github/workflows/build-release-artifacts.yml#L93) and tested in this repository (and the other showcase repositories) on [Mac 10.15 on CI](https://github.com/hydro-sdk/counter-app/blob/master/.github/workflows/debug-build-test.yml#L10). 

Could you try building and running `ts2hc` on your Mac 11.6.1 system? Just to see if you still receive the same error. 

`ts2hc` can be built by cloning https://github.com/hydro-sdk/hydro-sdk and and then running the following in the root of `hydro-sdk`:
```
npm install 
flutter pub get 
scripts/buildSdkTools.bash --skip-swid
```
That should build `.hydroc/0.0.1/sdk-tools/ts2hc-darwin-x64`. If that can at least start without crashing, that will narrow down the issue 🙂

**Comment by pvcresin** [comment]
@chgibb Thanks for the advice. Progress was made, but I was hit with another problem.

## Progress

After deleting the .hydroc folders, I ran `npx hydroc build --out-dir assets/ota --profile debug` and the build was successful! (Perhaps the download of the sdk was incomplete.)
The final contents of the .hydroc folder looks like this. 

<details>
<summary>Screenshot</summary>
<img src='https://user-images.githubusercontent.com/7846521/146665673-16a4036d-7a4e-42fa-a386-a84ad60fc387.png' width='250'>
</details>

## Problem

Attempting to build main.dart in debug mode failed. (VS Code -> Start Debugging)

Debug build: Success (empty application)
```dart
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
}
```

Debug build: Failed (I get an error when I add the import statement for runComponent.dart L1)
```dart
import 'package:hydro_sdk/runComponent/runComponent.dart';
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const RunComponent(
    project: "hydro-sdk",
    component: "counter-app",
  ));
}
```

Log

```sh
Launching lib/main.dart on AOSP on IA Emulator in debug mode...

lib/main.dart:1
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
: Error: Type 'SceneHost' not found.
../…/ui/sceneBuilder.dart:898
      required SceneHost sceneHost}) {
               ^^^^^^^^^
: Error: Type 'SceneHost' not found.
../…/ui/sceneHost.dart:6
class VMManagedSceneHost extends VMManagedBox<SceneHost> {
                                              ^^^^^^^^^

(Similar errors go on forever......)


FAILURE: Build failed with an exception.

* Where:
Script '/Users/toriyama/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1070

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/toriyama/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by chgibb** [comment]
The Dart code in `package:hydro_sdk/cfr/builtins/libs/dart/ui/` is auto-generated using [SWID](https://hydro-sdk.io/docs/design-documents/swid) and Flutter 2.0.6. It appears that `SceneHost` was removed at some point between Flutter 2.0.6 and Flutter 2.8.1. Do these errors persist if you try to run using Flutter 2.0.6?

**Comment by pvcresin** [comment]
@chgibb Thanks. When I used flutter v2.0.6, I didn't get the error I mentioned earlier. The next error came.

Step

1. Change flutter version by `cd flutter_sdk_folder`, `git checkout 2.0.6` (The flutter `downgrade` / `version` command and [fvm](https://fvm.app/) did not work properly with this repo.)

2. Check version `flutter --version`

```sh
Downloading Dart SDK from Flutter engine
Building flutter tool...
Flutter 2.0.6 • channel unknown • unknown source
Framework • revision 1d9032c7e1 (8 months ago) • 2021-04-29 17:37:58 -0700
Engine • revision 05e680e202
Tools • Dart 2.12.3
```

3. debug build -> error
```sh
StateError (Bad state: Insecure HTTP is not allowed by platform
```
/Users/toriyama/.pub-cache/git/hydro-sdk-340840bb39ed4bbea410c676abbc1acb0197c624/lib/runComponent/serviceAware.dart
![image](https://user-images.githubusercontent.com/7846521/146678035-7b2677f9-92ad-4681-9dc8-01d0938a1dfe.png)

"例外が発生しました" means "An exception has occurred".

**Comment by pvcresin** [comment]
@chgibb It's working! It's moving!

https://docs.flutter.dev/release/breaking-changes/network-policy-ios-android

> Starting with Android API 28 and iOS 9, these platforms disable insecure HTTP connections by default.

My Android emulator was Pixel 5 (API 28), so I had to deal with this.

![image](https://user-images.githubusercontent.com/7846521/146682056-5a251cce-26c0-44ab-918b-dc46356de9cd.png)

android/app/src/debug/AndroidManifest.xml: Add`<application android:usesCleartextTraffic="true"/>`
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.hydro_sdk.counter_app">
    <!-- Flutter needs it to communicate with the running application
         to allow setting breakpoints, to provide hot reload, etc.
    -->
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:usesCleartextTraffic="true" />
</manifest>
```

Debug build and hot reload is working!!
1. Run `npx hydroc run`
2. Start Debugging

https://user-images.githubusercontent.com/7846521/146682695-837d9567-4df7-4a08-a060-67b7f68c136d.mp4

**Comment by chgibb** [comment]
That's fantastic! I'm glad to see it working for you! 

I've started looking at verifying SDK-tool integrity after download. Flutter 2.8 support definitely won't be done until sometime in the New Year.

**Comment by pvcresin** [comment]
I know it's a lot of work to support Flutter v2.8.x.
Anyway, it worked for me in v2.0.6. Thanks, I'll close it.
